title: Coriana's Blog
author: Coriana
description: A simple blog hosted on GitHub Pages
baseurl: "" # the subpath of your site, leave empty for local development
url: "https://coriana.github.io" 
markdown: kramdown
theme: minima  # using minima theme for better defaults
permalink: /:year/:month/:day/:title
