title: Coriana's Blog
author: Coriana
description: A simple blog hosted on GitHub Pages
baseurl: "" # empty for user/org GitHub Pages at coriana.github.io
url: "https://coriana.github.io" 
markdown: kramdown
theme: minima  # using minima theme for better defaults
permalink: /:year/:month/:day/:title
